### ISSUE TITLE
小白问题请教

### ISSUE THREAD

**Issue by JimLee1996** [arthurliang/dockerfiles#1]
我在使用了您的SSR docker之后发现效果非常好。
为了满足自己的需要，在dockerfile里，加入了kcptun，具体可见[https://github.com/JimLee1996/dockerfiles/tree/master/SSR](https://github.com/JimLee1996/dockerfiles/tree/master/SSR)
在hub.docker.com上可以build pass([https://hub.docker.com/r/jimlee1996/ssr/](https://hub.docker.com/r/jimlee1996/ssr/))。但是在app.arukas.io上面一直显示deploying而最终运行失败。希望您能帮我看一下有啥问题，谢谢~

**Comment by arthurliang** [comment]
先在自己的试验机上运行下你的container，确保它本身没有问题。排除它本身无问题后，可能是arukas提供的服务有问题，你需要查看arukas的文档。

抱歉，我没有用过kcptun和arukas，不能帮上太多忙。

如果问题搞定，也可以回来留下你的解决之道，供其他人阅览。
